### ISSUE TITLE
DatabaseCleaner error when running RSpec

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/attr_masker#111]
As reported in https://github.com/riboseinc/attr_masker/issues/109#issuecomment-788687379

I'm working on a fix #110 , but stuck on the part where the gems `database_cleaner-*` with versions 2.x get installed when it shouldn't.  These newer versions removed the `called_externally?` method from `DatabaseCleaner`, which caused the errors seen in https://github.com/riboseinc/attr_masker/runs/2021552398?check_suite_focus=true#step:8:14

Then there's this seemingly unrelated error reported by CodeCov:

https://github.com/riboseinc/attr_masker/runs/2021552207?check_suite_focus=true#step:8:32

The questions remain:

1. How to reliably pin the versions for `database_cleaner-*`?
2. What is happening with CodeCov?  Is this something caused by something on our end?

**Comment by ribose-jeffreylau** [comment]
ping @skalee

**Comment by skalee** [comment]
Will fix. My bet is that I'm unintentionally overriding version constraints here:

https://github.com/riboseinc/attr_masker/blob/2391ea7c2826193fb608fedabde53a5e53716f6b/Gemfile#L7-L8

> How to reliably pin the versions for `database_cleaner-*`?

Good question. I'm working on that.

> What is happening with CodeCov? Is this something caused by something on our end?

As far as I understand, it has nothing to do with CodeCov. In one build it says: "Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected".

**Comment by ribose-jeffreylau** [comment]
That could be it (for both questions).  Thanks @skalee!

**Comment by skalee** [comment]
I'll fix it today.

**Comment by skalee** [comment]
Fixed in #114.
