### ISSUE TITLE
Upgrade gem version and make release

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/attr_masker#31]
@skalee since there have been many changes (positive changes) it's probably time to make a release.

Let me know when you're going to bump version, to make a release.

Then we'll change our code to adopt the latest version 👍

**Comment by skalee** [comment]
@ronaldtse AFAIK no version has been released before. Or at least querying Rubygems returns nothing (https://rubygems.org/search?utf8=%E2%9C%93&query=attr_masker).

**Comment by skalee** [comment]
But sure, I can release a 0.2.0. That said, I think I need to make some trivial Rails project just to prove everything works. Right now I am testing this gem against the test suite I made but I haven't tested it against any working Rails application yet.

**Comment by ronaldtse** [comment]
@skalee I've just pushed the current version to Rubygems. I suppose it is appropriate to include the trivial Rails project in CI tests so we know for sure it continues to work 👍

**Comment by skalee** [comment]
Thanks!

At the moment [Combustion](https://github.com/pat/combustion/) provides that dummy application. I prefer to stay with Combustion as it is minimalistic, very maintainable, and makes testing against different Rails versions pretty easy.

That said, I wanted to run this gem against some real application. Just in case.

**Comment by skalee** [comment]
@ronaldtse Do you think that introducing a CHANGELOG file is a good idea?

**Comment by ronaldtse** [comment]
@skalee you're right, we should have a CHANGELOG file to detail the differences between versions.

**Comment by skalee** [comment]
@ronaldtse Just created v0.1.1 GitHub release with minor bugfixes and major refactoring. However, I am not allowed to push it to RubyGems (I'm skalee@gmail.com).

Also, any recommendations on releasing? I've noticed that we're using GitHub releases, but anything else?

**Comment by ronaldtse** [comment]
@skalee I've released to rubygems.org via `rake release`. Currently we do the releasing so it's all good. Thanks!
