### ISSUE TITLE
Use Ruby 1.9 hash syntax

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/attr_masker#38]
Convert all hashes to the 1.9 `key: value` syntax.

**Comment by skalee** [comment]
@ronaldtse I understand this is related to this commit 1b2261b70599bf7123b9db7d399b4da55332510b, correct? I thought the old-fashioned hash is more readable here as the hash rockets can be easily aligned. But sure, I can fix it. All the other 1.8-style hashes have been replaced already.

**Comment by skalee** [comment]
Fixed.

**Comment by ronaldtse** [comment]
Thanks @skalee! Just wanted to keep things consistent.
