### ISSUE TITLE
Documentation should all be in RubyDocs

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/attr_masker#39]
We should create full RubyDocs documentation for the gem, and show it via GitHub Pages.

**Comment by skalee** [comment]
@ronaldtse Docs are already hosted on rubydoc.info: http://www.rubydoc.info/gems/attr_masker. We can host them on GitHub pages as well, but why?

Also, what about integrating Inch CI https://inch-ci.org/? This tool measures documentation completeness. I never used it in any of my projects, but perhaps it is useful.

**Comment by ronaldtse** [comment]
I was actually mistaken when I mentioned GitHub Pages. Anyway I'll do Inch CI and see what happens!
