### ISSUE TITLE
Incompatibility when using attr_masker with attr_encryptor

### ISSUE THREAD

**Issue by kwkwan** [riboseinc/attr_masker#51]
When the gem is used with another attribute modifier, such as `attr_encryptor` like below:

```ruby
attr_encryptor :test_field, key: proc { |k| k.key }
attr_masker :test_field, column_name: :encrypted_test_field
```

1. This configuration is highly dependent on the order of definition.
2. The masker (and the encryptor) will produce an error because the "masked" field is not a valid value to the encryptor (and vice versa)

Is there a way we can avoid this problem and have it compatible?

Thanks!

**Comment by ronaldtse** [comment]
@skalee any thoughts on this? Right now to make it master run one needs to comment out the "attr_encryptor" line.

**Comment by skalee** [comment]
@kwkwan @ronaldtse I don't think it's possible in a clean way with current architecture. Maybe I could invent some hackish workaround, but I don't think such invention is a good idea.

Also, please see issue #22, esp. my comment https://github.com/riboseinc/attr_masker/issues/22#issuecomment-322016226. I guess doing that will satisfy your need, I guess I'll now concentrate on that issue.

**Comment by skalee** [comment]
@kwkwan Could you please check if the current master works for you?

```ruby
attr_masker :test_field, column_names: %i[encrypted_test_field]
```

You may need to specify more columns if the crypted attribute spans on several columns, for instance if you store IV or seed in database.

**Comment by kwkwan** [comment]
I have tested it and encountered this issue:

```
OpenSSL::Cipher::CipherError: 
encryptor-3.0.0/lib/encryptor.rb:98:in `final'
encryptor-3.0.0/lib/encryptor.rb:98:in `crypt'
encryptor-3.0.0/lib/encryptor.rb:49:in `decrypt'
attr_encrypted-3.0.3/lib/attr_encrypted.rb:233:in `decrypt'
attr_encrypted-3.0.3/lib/attr_encrypted.rb:317:in `decrypt'
attr_encrypted-3.0.3/lib/attr_encrypted.rb:155:in `block (2 levels) in attr_encrypted'
attr_masker-f6f059309b1e/lib/attr_masker/attribute.rb:36:in `mask'
attr_masker-f6f059309b1e/lib/attr_masker/performer.rb:41:in `block in mask_object'
attr_masker-f6f059309b1e/lib/attr_masker/performer.rb:38:in `each'
attr_masker-f6f059309b1e/lib/attr_masker/performer.rb:38:in `reduce'
attr_masker-f6f059309b1e/lib/attr_masker/performer.rb:38:in `mask_object'
attr_masker-f6f059309b1e/lib/attr_masker/performer.rb:27:in `block (2 levels) in mask_class'
activerecord/lib/active_record/relation/delegation.rb:46:in `each'
activerecord/lib/active_record/relation/delegation.rb:46:in `each'
attr_masker-f6f059309b1e/lib/attr_masker/performer.rb:26:in `block in mask_class'
attr_masker-f6f059309b1e/lib/attr_masker/performer.rb:56:in `progressbar_for_model'
attr_masker-f6f059309b1e/lib/attr_masker/performer.rb:25:in `mask_class'
attr_masker-f6f059309b1e/lib/attr_masker/performer.rb:18:in `block in mask'
attr_masker-f6f059309b1e/lib/attr_masker/performer.rb:16:in `each'
attr_masker-f6f059309b1e/lib/attr_masker/performer.rb:16:in `mask'
attr_masker-f6f059309b1e/lib/tasks/db.rake:28:in `each'
attr_masker-f6f059309b1e/lib/tasks/db.rake:28:in `block (2 levels) in <top (required)>'
```

Could we make a new spec that includes the `attr_encrypted` gem as an example to ensure that the masked value is set and readable back?

**Comment by skalee** [comment]
@kwkwan I don't think that adding another spec dedicated for attr_masker is a good idea. It won't be general enough to be any useful. Also, I've created a test project in which some encrypted attribute is maskable, and it all works.

Can I learn more about your particular case? Like what cipher you use and what options you pass?

Here I attach few snippets from my test project in which masking works.

----

```ruby
class User < ApplicationRecord
  SECRET = "95557f51e0a3bbd255a56549c2c1bed7"

  attr_encrypted :password, key: SECRET, mode: :per_attribute_iv
  attr_masker :last_name, masker: ->(_hash) { _hash[:value][0] + "." }
  attr_masker :password, column_names: %i[encrypted_password encrypted_password_iv], masker: ->(_hash) { "1234" }
end
```

schema:

```ruby
  create_table "users", force: :cascade do |t|
    t.string "first_name"
    t.string "last_name"
    t.date "dob"
    t.string "email"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "encrypted_password"
    t.string "encrypted_password_iv"
  end
```

seeds:

```ruby
names = %w[
  Napoleon Hardison
  Anastasia Alequin
  Jeannine Darling
  Darnell Westervelt
  Ethelyn Hurwitz
  Meda Dillion
  Lucina Ott
  Bethann Alverez
  Cristina Sanson
  Vernell Jehle
  Celestina Gangi
  Lovie Pelton
  Fabian Gittens
  Jessika Rochford
  Faviola Amaro
  Earle Batson
  Alfreda Veselka
  Lisabeth Coomer
  Jeanetta Perri
  Thomasina Christensen
]

for (first, last) in names.each_slice(2)
  User.where(first_name: first, last_name: last).first_or_create!
end
```

Running `rake db:mask` works well, and after doing that `User.first.password` returns `"1234"` as expected.

**Comment by kwkwan** [comment]
It works now.  Thanks!

**Comment by ronaldtse** [comment]
Thanks @skalee @kwkwan !
