### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by skalee** [riboseinc/attr_masker#71]
Already started, but there are some dependency issues, probably due to missing dependencies, which cause build failures.

**Comment by skalee** [comment]
@ronaldtse I have mixed feelings about this migration due to my so far experience with this gem and GHA.

Cons:

1. GHA is actually slower than Travis. This is because in Travis I can define a tiny build matrix which covers all the representative cases (13 jobs), whereas in GHA I need to do a cartesian product, which results in over 60 jobs in case of this gem. Excluding from matrix is possible, but often tedious (see: https://github.community/t5/GitHub-Actions/Improve-matrix-exclusion-feature/m-p/44716). The difference in build times is not big though. Also, I think that I can shave off several minutes with caching both in case of Travis and GHA.
2. GHA does not allow to re-run a failed job. And in the past we had several issues with random tests failures, which were difficult to understand and fix. That means that if some project has fragile test suite, GHA-powered CI becomes useless. Especially when build matrix is huge, like in this very gem, because every job increases a chance of failure.
3. GHA does not allow to specify builds which are allowed to fail, like it's common to do in tests against Ruby or Rails HEAD (see: https://github.community/t5/GitHub-Actions/continue-on-error-allow-failure-UI-indication/td-p/37033). A workaround exists, but it is very inconvenient in use.

Pros:

1. On the other hand, huge build matrix already helped me to detect one very subtle issue with tests, which was happening under very specific circumstances.
2. We can expect that more features will be added to GHA over time.

The choice is yours. Anyway, I have already prepared a GHA workflow, and proven that it works. Example run: https://github.com/riboseinc/attr_masker/actions/runs/33097323.

**Comment by skalee** [comment]
I've just found a button for re-running jobs. There are two limitations however: it is required to run all the jobs in a workflow, and that the button is hidden for successful jobs.

**Comment by ronaldtse** [comment]
@skalee thanks for creating the GHA workflow. I think both points 1 and 3 are definitely valid, and the caveats you found with re-running are true. That said, we have benefitted from GHA allowing more parallel jobs than Travis and so far it's working.

So let's get the new branch merged in (with an update to the README badges). Thanks!
