### ISSUE TITLE
Bring CodeCov back

### ISSUE THREAD

**Issue by skalee** [riboseinc/attr_masker#95]
It has disappeared when we migrated to GHA, and must be reconfigured.

@ronaldtse Please add a coverage upload token to this repo. Precisely:

1. Find "Repository Upload Token" on this page: https://codecov.io/gh/riboseinc/attr_masker/settings
2. Add it to this repo as a secret variable named `CODECOV_TOKEN`.

**Comment by skalee** [comment]
@ronaldtse ping

**Comment by ronaldtse** [comment]
@skalee token added!

**Comment by skalee** [comment]
It is resolved since then, that is coverage reports are uploaded to CodeCov properly.
