### ISSUE TITLE
Make new release after #96

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/attr_masker#99]
#96 removes the unnecessarily polluting executables. Need to make a new release.

Ping @skalee

**Comment by skalee** [comment]
Oh dear, it looks like the last release is from 2017, and about 80 commits behind master. Investigation needed.

Also, I need to be added as one of the gem owners in order to make the release.

Sorry for late reply, I overlooked this one.

**Comment by skalee** [comment]
Forgot to ping @ronaldtse:

> I need to be added as one of the gem owners in order to make the release.

**Comment by ronaldtse** [comment]
@skalee will add you once I get back to the computer

**Comment by ronaldtse** [comment]
@skalee you now have gem owner access.

**Comment by skalee** [comment]
Hmm, `gem owner attr_masker` still does not mention me. Perhaps you've added me elsewhere accidentally, @ronaldtse?

**Comment by ronaldtse** [comment]
```
gem owner attr_masker -a skalee@gmail.com
Adding skalee@gmail.com: User has already been taken
```

You're already added -- did you check your email to "accept"?

Also sent you an email... can you please reply? Thanks!

**Comment by skalee** [comment]
Stupid me. Indeed, I haven't checked my mailbox for a couple of days.

**Comment by skalee** [comment]
Done in 2391ea7c2826193fb608fedabde53a5e53716f6b.
